server:
  port: 8080   # Gateway runs on 8080

spring:
  application:
    name: api-gateway   # this must match your config repo file name (api-gateway.yml)
  config:
    import: optional:configserver:http://${CONFIG_SERVER_URL:localhost}:8888

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_URL:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always