package com.springcloud.order_service.events;

public enum OrderStatus
{
    CREATED, RESTAURANT_CONFIRMED,RESTAURANT_REJECTED, PAYMENT_PENDING, ORDER_CONFIRMED, DELIVERY_ASSIGNED, ORDER_COMPLETED,
    ORDER_CANCELLED,DELIVERY_FAILED
}
