server:
  port: 8083

spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_URL:localhost}:8888

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_URL:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true